openapi: 3.0.0
info:
  title: RAG Agent API
  description: API for the Retrieval-Augmented Generation agent that answers questions about book content
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Development server
  - url: https://api.example.com
    description: Production server

paths:
  /query:
    post:
      summary: Submit a question to the RAG agent
      description: Accepts a user question, retrieves relevant book content, and returns an answer with source references
      operationId: query
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryRequest'
      responses:
        '200':
          description: Successful response with answer and sources
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryResponse'
        '400':
          description: Bad request - invalid input parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      description: API key for authentication

  schemas:
    QueryRequest:
      type: object
      required:
        - question
      properties:
        question:
          type: string
          description: The user's question about book content
          example: "What are the key principles of machine learning?"
          minLength: 1
          maxLength: 1000
        top_k:
          type: integer
          description: Number of documents to retrieve (default: 5)
          minimum: 1
          maximum: 20
          default: 5
          example: 5
        include_sources:
          type: boolean
          description: Whether to include source citations in response (default: true)
          default: true
          example: true

    QueryResponse:
      type: object
      required:
        - answer
        - sources
        - query_id
      properties:
        answer:
          type: string
          description: The agent's answer to the user's question
          example: "The key principles of machine learning include supervised learning, unsupervised learning, and reinforcement learning..."
        sources:
          type: array
          description: List of source references used to generate the answer
          items:
            $ref: '#/components/schemas/SourceReference'
        query_id:
          type: string
          description: Unique identifier for the query
          example: "query-12345-abcde"

    SourceReference:
      type: object
      required:
        - content
        - metadata
        - relevance_score
      properties:
        content:
          type: string
          description: Excerpt from the source document
          example: "Machine learning is a subset of artificial intelligence that enables systems to learn and improve from experience..."
        metadata:
          type: object
          description: Metadata about the source
          properties:
            url:
              type: string
              description: URL of the source
              example: "https://example.com/book/chapter1"
            section_title:
              type: string
              description: Title of the section
              example: "Introduction to Machine Learning"
            page_number:
              type: integer
              description: Page number in the book
              example: 42
        relevance_score:
          type: number
          description: Relevance score of the source to the query
          minimum: 0
          maximum: 1
          example: 0.85

    ErrorResponse:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          description: Error code
          example: "QUERY_ERROR"
        message:
          type: string
          description: Human-readable error message
          example: "Question must be between 1 and 1000 characters"